from __future__ import annotations

from pathlib import Path

DEFAULT_KEYWORDS = [
    "amazing",
    "incredible",
    "best",
    "perfect",
    "excellent",
    "outstanding",
    "fantastic",
    "wonderful",
    "superb",
    "flawless",
    "ultimate",
    "unbeatable",
    "top-notch",
    "premium",
    "high quality",
    "top quality",
    "world class",
    "five star",
    "5 star",
    "must have",
    "must-have",
    "life changing",
    "life-changing",
    "revolutionary",
    "game changer",
    "game-changer",
    "cutting edge",
    "state of the art",
    "next level",
    "next-level",
    "best ever",
    "number one",
    "buy now",
    "order now",
    "order today",
    "shop now",
    "get yours",
    "get yours now",
    "dont miss",
    "don't miss",
    "limited time",
    "limited offer",
    "special offer",
    "exclusive offer",
    "free shipping",
    "fast shipping",
    "money back",
    "money-back",
    "guaranteed",
    "guaranteed satisfaction",
    "satisfaction guaranteed",
    "risk free",
    "risk-free",
    "no risk",
    "no-risk",
    "limited stock",
    "while supplies last",
    "hurry up",
    "act fast",
    "highly recommend",
    "strongly recommend",
    "100% recommend",
    "best purchase",
    "best buy",
    "worth every penny",
    "great value",
    "bargain",
    "deal",
    "low price",
    "cheapest",
    "save big",
    "discount",
    "sale",
    "hot deal",
    "special deal",
    "must buy",
    "must-buy",
    "buy this",
    "buy it now",
    "add to cart",
    "add-to-cart",
    "click here",
    "click now",
    "top seller",
    "best seller",
    "bestseller",
    "best-selling",
    "approved",
    "official",
    "authentic",
    "genuine",
    "original",
    "durable",
    "long-lasting",
    "long lasting",
    "premium quality",
    "superior",
    "ultra",
    "mega",
    "super",
    "awesome",
    "unbelievable",
    "top rated",
    "highly rated",
    "top rating",
    "customer favorite",
    "fan favorite",
    "best choice",
    "great choice",
    "perfect gift",
    "ideal gift",
    "limited edition",
    "brand new",
    "new and improved",
    "improved",
    "exclusive",
    "special",
    "unique",
    "luxury",
    "deluxe",
    "extra strong",
    "powerful",
    "best quality",
    "high grade",
    "first class",
]


def default_keywords_path() -> Path:
    return Path(__file__).resolve().parent.parent / "data" / "promo_keywords.txt"


def load_keywords(path: str | Path | None = None) -> list[str]:
    path = Path(path) if path else default_keywords_path()
    if path.exists():
        content = path.read_text(encoding="utf-8", errors="ignore").splitlines()
        keywords = [line.strip() for line in content if line.strip() and not line.strip().startswith("#")]
        return keywords or DEFAULT_KEYWORDS
    return DEFAULT_KEYWORDS
